[toolchain]
channel = "1.92"
components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt",
]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
